workflow arm

diff --git a/.github/workflows/e2e-arm.yaml b/.github/workflows/e2e-arm.yaml
--- a/.github/workflows/e2e-arm.yaml
+++ b/.github/workflows/e2e-arm.yaml
@@ -3,14 +3,29 @@ on: [push, pull_request]
 jobs:
   test:
     runs-on: self-hosted
+    strategy:
+      fail-fast: true
+      matrix:
+        target:
+        - linux-arm64-e2e
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-go@v2
-        with:
-          go-version: "1.16.15"
-      - run: go version
-      - run: date
-      - name: Run e2e
-        run: |
-          GOARCH=arm64 PASSES='build e2e' CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./test.sh 2>&1 | tee test.log
-          ! egrep "(--- FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test.log
+    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
+    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
+      with:
+        ref: main
+        go-version: "1.19.7"
+    - run: date
+    - env:
+        TARGET: ${{ matrix.target }}
+      run: |
+        echo "${TARGET}"
+        case "${TARGET}" in
+          linux-arm64-e2e)
+            PASSES='build release e2e' CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./scripts/test.sh 2>&1 | tee test.log
+            ! grep -E "(--- FAIL:|FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test.log
+            ;;
+          *)
+            echo "Failed to find target"
+            exit 1
+            ;;
+        esac
diff --git a/.github/workflows/tests-arm.yaml b/.github/workflows/tests-arm.yaml
--- a/.github/workflows/tests-arm.yaml
+++ b/.github/workflows/tests-arm.yaml
@@ -3,22 +3,41 @@ on: [push, pull_request]
 jobs:
   test:
     runs-on: self-hosted
+    strategy:
+      fail-fast: false
+      matrix:
+        target:
+        - linux-arm64-integration-1-cpu
+        - linux-arm64-integration-2-cpu
+        - linux-arm64-integration-4-cpu
+        - linux-arm64-unit-4-cpu-race
     steps:
-      - uses: actions/checkout@v2
-      - name: install dependencies
-        run: |
-          sudo apt install -y git gcc
-      - uses: actions/setup-go@v2
-        with:
-          go-version: "1.16.15"
-      - run: go version
-      - run: date
-      - name: Run tests
-        run: |
-          GOARCH=arm64 PASSES='fmt bom dep' ./test.sh
-          GOARCH=arm64 CPU=1 PASSES='integration' RACE='false' ./test.sh
-          GOARCH=arm64 CPU=2 PASSES='integration' RACE='false' ./test.sh
-          GOARCH=arm64 CPU=4 PASSES='integration' RACE='false' ./test.sh
-          GOARCH=arm64 PASSES='unit' RACE='true' CPU='4' ./test.sh -p=2
-          GOARCH=arm64 PASSES='build' ./test.sh
-          GO_BUILD_FLAGS='-v -mod=readonly' GOARCH=arm64 ./build.sh
+    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
+    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
+      with:
+        ref: main
+        go-version: "1.19.7"
+    - run: date
+    - env:
+        TARGET: ${{ matrix.target }}
+      run: |
+        mkdir "${TARGET}"
+        export JUNIT_REPORT_DIR=$(realpath ${TARGET})
+        case "${TARGET}" in
+          linux-arm64-integration-1-cpu)
+            GOARCH=arm64 CPU=1 PASSES='integration' RACE='false' ./scripts/test.sh
+            ;;
+          linux-arm64-integration-2-cpu)
+            GOARCH=arm64 CPU=2 PASSES='integration' RACE='false' ./scripts/test.sh
+            ;;
+          linux-arm64-integration-4-cpu)
+            GOARCH=arm64 CPU=4 PASSES='integration' RACE='false' ./scripts/test.sh
+            ;;
+          linux-arm64-unit-4-cpu-race)
+            GOARCH=arm64 PASSES='unit' RACE='true' CPU='4' ./scripts/test.sh -p=2
+            ;;
+          *)
+            echo "Failed to find target"
+            exit 1
+            ;;
+        esac
